### ISSUE TITLE
Importing a Pull Request

### ISSUE THREAD

**Issue by DarthHater** [google/copybara#54] opened 2018-05-15 19:02 UTC
Hi there!

I'm gearing up to do a demo of copybara for @sonatype tomorrow, and I was curious, what do you all do to import a pull request? I can add this to the docs as an example as well.

What I basically want to do is:

- I have a private source repo
- PR comes in from public destination repo
- Run copybara to bring the PR in to the source repo (so we can noodle on it, make adjustments if we need to)
- Merge that PR
- Run copybara and have the changes make it out to the destination

I see some stuff around the source PR, etc... but figured I would ask more so about workflow related to this.

Thanks!

**Comment by mikelalcon** [comment] 2018-05-15 19:33
Hi,
This is a really good question as we do several things. It really depends on what the user wants to use. Here are a few things we do (I might add more stuff if I remember later):

   - Importing PR from SoT should be done with a CHANGE_REQUEST workflow.
 
   - You probably want to set in your workflow set_rev_id = False. Since it is pure informational and probably
      confusing for git -> git.

   - We usually add metadata.save_author() as a transformation (and then metadata.restore_author in the private -> public export). This way we attribute the change to the original author.

   - If you add metadata.expose_label("COPYBARA_INTEGRATE_REVIEW") in the import ( and maybe in the export, depends on what you end with internally) it will automatically fake merge the original public PR when you export from private -> public.

  - You can also use:
     metadata.expose_label("GITHUB_PR_NUMBER", new_name ="Closes", separator=" #")

    to add the typical Closes #1234 GitHub tag

 - Or you can use it to create a link to the original PR url.

  - GITHUB_BASE_BRANCH_SHA1 or other labels to construct messages

  - You can also do:
      metadata.replace_message("BEGIN_PUBLIC\n${COPYBARA_CURRENT_MESSAGE}\nEND_PUBLIC")
     if you want to wrap the original message in public tags so that when you export you remove non public stuff.

**Comment by mikelalcon** [comment] 2018-05-15 21:15
Thanks very much for the examples! that would be great

Yeah we have two workflows one for private -> public (ITERATIVE) and one for public -> private (CHANGE_REQUEST). This assumes the source of truth is 'private' repo. You can do the other way around changing the modes if 'public' is the SoT.

**Comment by mikelalcon** [comment] 2018-06-14 17:39
It would be:

```
core.workflow(
    origin = git.github_pr_origin(
        url = "https://github.com/some/project",
        use_merge = True,  <--- not necessary but if you mutate your config a lot you might need this.
     ),
    mode = "CHANGE_REQUEST",
    destination  =  <--- can be git.destination as you have or git.github_pr_destination if you want approval before submit.
   transformations = [
         metadata.save_author(),
         metadata.expose_label("COPYBARA_INTEGRATE_REVIEW"),
    ]
)
```

You can expose more labels, construct messages with them, etc, You have all these labels available: 
https://github.com/google/copybara/blob/master/docs/reference.md#git.github_pr_origin

**Comment by DarthHater** [comment] 2018-06-14 18:08
I think what I am curious about is how you specify which PR you want to import, or does this workflow import ALL PRs?

**Comment by DarthHater** [comment] 2018-06-14 18:30
I am guessing it's by using a URL like: `https://github.com/project/pull/123`, just want to confirm!

**Comment by mikelalcon** [comment] 2018-06-14 19:30
Ahh I see :) Yeah you pass need to pass the PR as parameter. The whole url or just 123 should do it.

**Comment by DarthHater** [comment] 2018-06-14 19:38
Ok, I figured that out myself. Now I'm at a bit of a fun impass:

```
core.workflow(
    name = "importPrFromPublic",
    origin = git.github_pr_origin(
        url = destinationUrl,
        use_merge = True,
    ),
    destination = git.destination(
        url = sourceUrl,
        fetch = "master",
        push = "master",
    ),
    mode = "CHANGE_REQUEST",
    set_rev_id = False, 
    # Change path to the folder you want to publish publicly
    origin_files = glob(["**"]),
    destination_files = glob(["**"], exclude = [STUFF]),

    authoring = authoring.pass_thru("Dude <email@email.com>"),
    transformations = [
      metadata.save_author(),
      metadata.expose_label("COPYBARA_INTEGRATE_REVIEW"),
      metadata.expose_label("GITHUB_PR_NUMBER", new_name ="Closes", separator=" #"),
      core.move("README.md", ".copybara/public/README.md")
    ],
)
```

That's the config I have currently.

Running like so:

`docker run -v ~/.ssh:/root/.ssh -v ~/.gitconfig:/root/.gitconfig -v "$(pwd)":/usr/src/app COPYBARA_WORKFLOW=importPrFromPublic -e COPYBARA_SOURCEREF='22' -it copybara copybara`

```
Copybara source mover (Version: Unknown version)
Task: GitHub PR Origin: Resolving reference 22
INFO: GitHub credentials not found in ~/.git-credentials. Assuming the repository is public.
Task: Integrating change from https://github.com/sonatype-nexus-community/search-maven-org/pull/22 from sonatype-nexus
-community:test-compilation-errors c4bfa70355ed199a8d42608448106fe406cc0889
ERROR: Conflict detected while rebasing /root/copybara/temp/workdir2997047483223812704/checkout to f6ad687da6947037600
0651a79c08ffdfbdb816c. Git output was:
First, rewinding head to replay your work on top of it...
Applying: Public export of search.maven.org code:
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
Auto-merging tslint.json
CONFLICT (add/add): Merge conflict in tslint.json
Auto-merging tsconfig.json
CONFLICT (add/add): Merge conflict in tsconfig.json
Auto-merging src/tsconfig.spec.json
CONFLICT (add/add): Merge conflict in src/tsconfig.spec.json
Auto-merging src/styles.scss
CONFLICT (add/add): Merge conflict in src/styles.scss
Auto-merging src/polyfills.ts
CONFLICT (add/add): Merge conflict in src/polyfills.ts
Auto-merging src/main.ts
CONFLICT (add/add): Merge conflict in src/main.ts
Auto-merging src/index.html
CONFLICT (add/add): Merge conflict in src/index.html
Auto-merging src/environments/environment.ts
CONFLICT (add/add): Merge conflict in src/environments/environment.ts
Auto-merging src/environments/environment.prod.ts
CONFLICT (add/add): Merge conflict in src/environments/environment.prod.ts
Auto-merging src/assets/i18n/en.json
CONFLICT (add/add): Merge conflict in src/assets/i18n/en.jsonAuto-merging src/app/app.module.ts
CONFLICT (add/add): Merge conflict in src/app/app.module.ts
Auto-merging src/app/app.component.ts
CONFLICT (add/add): Merge conflict in src/app/app.component.tsAuto-merging src/app/app.component.spec.ts
CONFLICT (add/add): Merge conflict in src/app/app.component.spec.ts
Auto-merging src/app/app.component.html
CONFLICT (add/add): Merge conflict in src/app/app.component.html
Auto-merging package.json
CONFLICT (add/add): Merge conflict in package.json
Auto-merging package-lock.json
CONFLICT (add/add): Merge conflict in package-lock.json
Auto-merging karma.conf.js
CONFLICT (add/add): Merge conflict in karma.conf.js
Auto-merging e2e/app.po.ts
CONFLICT (add/add): Merge conflict in e2e/app.po.ts
Auto-merging e2e/app.e2e-spec.ts
CONFLICT (add/add): Merge conflict in e2e/app.e2e-spec.ts
Patch failed at 0001 Public export of search.maven.org code:
The copy of the patch that failed is found in: LOCATION

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

All of those files exist in both locations, so this is mind boggling currently. 

I took a look at the patch file and it is truly treating those as new file mode, which is odd.

Any ideas what I'm doing wrong? Maybe my copy of copybara is too old and you've fixed some bug since then?

**Comment by mikelalcon** [comment] 2018-06-14 20:04
Can you add to the git.destination
destination = git.destination(
      integrates = []
)
?

It turns out this is the first time we use integrates for git -> git. And the git destination automatically tries to integrate the PR :)

**Comment by DarthHater** [comment] 2018-06-14 21:06
That worked! However it didn't do quite what I thought it was going to do. When I ran it, it ended up merging that PR into master on our private repo, and I imagine that is because I have:

```
    destination = git.destination(
        url = sourceUrl,
        integrates = [],
        fetch = "master",
        push = "master",
    ),
```

I had expected that it would create a new PR on the private side, which is what I want to end up with. Do I just remove the `push = "master"`, and then that is the expected behavior?

**Comment by mikelalcon** [comment] 2018-06-14 21:13
That was the part I was talking about before:
 destination  =  <--- can be git.destination as you have or git.github_pr_destination if you want approval before submit.

You probably want git.github_pr_destination

**Comment by DarthHater** [comment] 2018-06-14 21:14
AH! I'm a dummy, lemme give it a go.

**Comment by DarthHater** [comment] 2018-06-14 21:19
Ok, almost there, I swear.

```
Copybara source mover (Version: Unknown version)
Task: Cleaning output directory
ERROR: /usr/src/app/copy.bara.sky:34:19: Traceback (most recent call last):
        File "/usr/src/app/copy.bara.sky", line 28
                core.workflow(name = "importPrFromPublic", origi...), <7 more arguments>)
        File "/usr/src/app/copy.bara.sky", line 34, in core.workflow
                git.github_pr_destination(url = sourceUrl)
git@github.com:org/internal_repo_name.git is not a valid git url
ERROR: Error loading config file
```

It would seem that git ssh urls do not work with github_pr_destination? This seems kinda odd, maybe an old bug?

**Comment by mikelalcon** [comment] 2018-06-14 21:20
That is an actual bug :) . Let me do a quick fix.

We usually use https://github.com/foo/bar like urls.

**Comment by DarthHater** [comment] 2018-06-14 21:21
Awesome. Go ahead and close this issue if you want when you fix it, and I'll grab the latest and go from there.

**Comment by mikelalcon** [comment] 2018-06-14 21:38
K sending the fix. Note that for using github_pr_destination you'll need to add a GH token with access to the private repo and create Pull Request. This is because we use GitHub API for creating the  Pull Request

The file is:
  
    $HOME/.git-credentials

And the content has to be something like: 
```
https://ESCAPED_GH_LOGIN_EMAIL:TOKEN@github.com
```
For example:
```
https://example.person%40gmail.com:123456789abcdef123456789abcdef@github.com
```
Note that '%40' is used instead of '@'

You can use other kind of credential stores too (If you use 'cache' credential store you'll need to do something like 'git fill' before calling Copybara, since we don't read from the tty).

**Comment by mikelalcon** [comment] 2018-06-14 21:40
You can also use --github-destination-pr-create false and go to GitHub and create the PR yourself with the branch we created.

**Comment by DarthHater** [comment] 2018-06-14 21:42
Makes sense. Lemme see where I get fumbling with things!

**Comment by mikelalcon** [comment] 2018-06-14 21:51
Change is in GitHub master now

**Comment by DarthHater** [comment] 2018-06-14 21:52
I guess just to be razor sharp, for the GH token, what is the least amount of permissions I need?

In terms of scopes I see:

<img width="534" alt="screen shot 2018-06-14 at 1 51 31 pm" src="https://user-images.githubusercontent.com/5544326/41440185-1ac4a056-6fda-11e8-94ca-abe3ac9802d7.png">

**Comment by DarthHater** [comment] 2018-06-14 22:06
One other thing I noticed is there is no ability to do:

`        integrates = [],`

for the github_pr_destination. This landed me back where I was earlier. I assume however I can pass:

`--git-destination-ignore-integration-errors`?

**Comment by mikelalcon** [comment] 2018-06-14 22:09
Ahh I see.  Adding the option now :)

**Comment by DarthHater** [comment] 2018-06-14 23:12
So in looking at this you need scope `repo` (which stinks but that's a GitHub thing, not your fault).

We got this working! A couple last questions:

When I imported this the title came across as:

<img width="783" alt="screen shot 2018-06-14 at 3 11 11 pm" src="https://user-images.githubusercontent.com/5544326/41442747-394e4616-6fe5-11e8-98ee-da3ab0d96121.png">

It would be ideal if it was the original title and the original description. I'm sure this is possible, just not sure how to do it as the options I saw make it look like you can override it, but I was thinking it would flow across like the original.

**Comment by DarthHater** [comment] 2018-06-15 17:07
Ok a few more questions:

* The commit that made it in to our internal repo had a Closes # on it, with the correct number, but it is on the commit and not the PR, as a result it didn't close the public PR when I merged it. 
* Curious how to maintain the Title and Description, as those would be valuable (in addition to the Merge sha into sha message, that's actually great too)

I'm super close to getting this all working and I'm really stoked. As soon as I got it in place I'll fashion up some examples for your docs related to this + using it with Docker.

**Comment by DarthHater** [comment] 2018-06-15 17:19
I think I just figured out my first question. I noticed that for Closes # number, it is referring to the PR number of that internal repo (duh). I figured I can do something like this:

`metadata.expose_label("GITHUB_PR_NUMBER", new_name ="Closes org/reponame", separator="#"),`

However, is there a property I can just use there that will output the org/reponame rather than hard coding it?

**Comment by mikelalcon** [comment] 2018-06-15 17:20
You can use `metadata.squash_notes(use_merge = False)` as a transformation when importing.

You also can use `metadata.replace_message("${GITHUB_PR_TITLE}\n\n${GITHUB_PR_BODY}")` or something like that.

**Comment by DarthHater** [comment] 2018-06-15 17:56
Just posting this for others, I got it to get the link to close the external PR right by using:

`metadata.expose_label("GITHUB_PR_NUMBER", new_name ="Closes", separator=" " + publicRepoName + "#"),`

**Comment by mikelalcon** [comment] 2018-06-15 18:14
Note that if you use Closes #123 like approach you wont need COPYBARA_INTEGRATE_REVIEW.

IOW:
   - Closes #123 approach closes the PR when it goes from internal -> external
   - COPYBARA_INTEGRATE_REVIEW approach:  does a fake merge of the PR when going from internal -> external.

**Comment by DarthHater** [comment] 2018-06-15 18:17
Dude I was JUST about to ask that, haha, literally just deleted my reply.

Ok so on that note, I DID do that, but when I did the export from private to public it DIDN'T close it. I think this is because I do:

```
metadata.squash_notes(prefix = 'Public export of search.maven.org code:\n\n', show_description = False),
```

I imagine that the message gets wiped out in the process of doing that? 

Figuring out the process around all of this is the tricky part more than anything, the tool works wonderfully, ps.

**Comment by mikelalcon** [comment] 2018-06-15 18:34
Can you add a 
```
metadata.expose_label("COPYBARA_INTEGRATE_REVIEW")
```
in the private -> public workflow, but as a last transformation? (so that other message changes don't affect it)

**Comment by DarthHater** [comment] 2018-06-15 18:39
Will do, giving that a shot now!

**Comment by DarthHater** [comment] 2018-06-15 18:52
Worked! You are the best @mikelalcon , I'll get on some examples for the project, thanks for weathering through this with me.

**Comment by mikelalcon** [comment] 2018-06-15 18:56
You are welcome! I think at some point we might want to build a github.bara.sky library that exposes a library for constructing this common workflows.

**Comment by DarthHater** [comment] 2018-06-15 18:57
If you give me some pointers I'd gladly take that on as a task.

**Comment by mikelalcon** [comment] 2018-06-15 19:09
The idea would be to have a file like:

github.bara.sky:

```
def github_to_private_github_sot(private_url, public_url, branch="master", use_integrates=True,to_private_transformations = [], to_public_transformations = None):
      core.workflow(
          name = "import_pr",
         mode = "CHANGE_REQUEST",
        ...
       transformations =  to_private_transformations + [some internal ones ]
      )
      core.workflow(
         name = "export",
         mode = "ITERATIVE",
         ...
         transformations = to_public_transformations** + [some internal ones]
       )
```

** to_public_transformations needs to do core.reverse(to_private_transformations) if value is None.

The biggest two issues are:
   -  To find the right abstractions to make it easy to use but also be extensible
   - How we distribute them. We might bundle them in the jar and have a special namespace in load().
      Not sure about this. Probably we can start by asking users to just copy the file.

**Comment by ob** [comment] 2019-11-07 22:12
I'm trying to import a pull request in a very similar way:

```
core.workflow(
    name = "import_pr_from_github",
    mode = "CHANGE_REQUEST",
    origin = git.github_pr_origin(
        url = github_url,
        submodules = "NO",
        baseline_from_branch = True,
    ),
    destination = git.destination(
        url = path_to_local_repo,
        fetch = "master",
    ),
    origin_files = glob(["**"]),
    destination_files = glob(
        ["subdir/**"],
        exclude = [
            "subdir/some-file",
        ],
    ),
    authoring = authoring.pass_thru("Default email <default@defatult.com>"),
    transformations = [
        core.move("", "subdir"),
        metadata.save_author(),
        metadata.expose_label("COPYBARA_INTEGRATE_REVIEW"),
        metadata.expose_label("GITHUB_PR_NUMBER", new_name = "Closes", separator = " #"),
    ],
)
```

but when I call it, I get:

```
% copybara copy.bara.sky import_pr_from_github https://github.com/ob/package/pull/7
Nov 07, 2019 2:06:31 PM com.google.copybara.Main configureLog
INFO: Setting up LogManager
Copybara source mover (Version: Unknown version)
Task: GitHub PR Origin: Resolving reference https://github.com/ob/package/pull/7
ERROR: Pull Request not found: GitHub API call failed with code 404 The request was GET repos/ob/package/pulls/7Response:
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#get-a-single-pull-request"}

  CAUSED BY: GitHub API call failed with code 404 The request was GET repos/ob/package/pulls/7Response:
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#get-a-single-pull-request"}

```

Any idea what I'm doing wrong?

**Comment by hsudhof** [comment] 2019-11-07 22:33
Nothing really, the issue is the same as in https://github.com/google/copybara/issues/101 -  you should specify the credentials to be used in a credentials helper (--git-credential-helper-store-file)

**Comment by ob** [comment] 2019-11-08 19:03
@hsudhof I have `~/.git-credentials` properly set up though... and [here](https://github.com/google/copybara/blob/master/java/com/google/copybara/git/GitHubOptions.java#L81) looks like it picks it up if you don't pass the argument. At any rate, I tried:

```
% copybara copy.bara.sky import_pr_from_github --git-credential-helper-store-file ~/.git-credentials https://github.com/ob/package/pull/7
Nov 08, 2019 10:59:18 AM com.google.copybara.Main configureLog
INFO: Setting up LogManager
Copybara source mover (Version: Unknown version)
Task: GitHub PR Origin: Resolving reference https://github.com/ob/package/pull/7
ERROR: GitHub API call failed with code 403 The request was GET repos/ob/package/pulls/7Response:
{"message":"API rate limit exceeded for 216.52.21.2. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
```

So it does look like the option is not taking effect.

**Comment by hsudhof** [comment] 2019-11-08 20:19
Good point, there is a regression, I have merged a fix.

**Comment by adamhowardprice** [comment] 2022-02-15 16:54
Nevermind, I got this working with a Github API token

**Closed** 2022-02-15 16:54 UTC
